---

- name: Ensure the Supervisor service is running
  service: name=supervisor state=started enabled=yes

- name: Create the Supervisor config file for {{ notify_application_name }}
  template: src=supervisor_{{ notify_application_name }}.conf.j2
            dest=/etc/supervisor/conf.d/{{ notify_application_name }}.conf

- name: Create the {{ notify_application_name }} log directory
  file: path={{ notify_log_dir }}
        owner={{ notify_user }}
        group={{ notify_group }}
        state=directory

- name: Check for an existing notify logfile
  stat:
    path: "{{ notify_log_file }}"
  register: p

- name: Create (or retain) the {{ notify_application_name }} log file
  file:
    path: "{{ notify_log_file }}"
    owner: "{{ notify_user }}"
    group: "{{ notify_group }}"
    state: '{{ "file" if  p.stat.exists else "touch" }}'

- name: Re-read the Supervisor config files
  supervisorctl: name={{ notify_application_name }} state=present
