---
- name: ICFP Contest 2019 infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - env_vars/aws.yml

  # This file assumes you have already set-up the security groups
  tasks:
    - name: Launch master
      local_action:
        module: ec2
        region: "{{ ec2_region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ master_instance_type }}"
        image: "{{ ami_image }}"
        group: "{{ master_security_group }}"
        instance_tags:
          Role: "master"
        exact_count: 1
        count_tag:
          Role: "master"
        wait: yes
      register: mst

    - name: Associate elastic IP with master
      ec2_eip:
        device_id: "{{ item.id }}"
        private_ip_address: "{{ item.private_ip}}"
        region: "{{ ec2_region }}"
        ip: "{{ master_public_ip }}"
        in_vpc: yes
      with_items: "{{ mst.tagged_instances }}"

    - name: Add new instance to host group
      add_host:
        hostname: "{{ master_public_ip }}"
        groupname: master

    - name: Wait for master SSH to come up
      wait_for:
        host: "{{ master_public_ip }}"
        port: 22
        delay: 60
        timeout: 900
        state: started

    - name: Launch {{ num_workers }} workers
      local_action:
        module: ec2
        region: "{{ ec2_region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ worker_instance_type }}"
        image: "{{ ami_image }}"
        group: "{{ worker_security_group }}"
        # spot_price: "{{ worker_spot_price }}"
        # spot_wait_timeout: "{{ spot_wait_timeout }}"
        # instance_initiated_shutdown_behavior: "terminate"
        instance_tags:
          Role: "worker"
        exact_count: "{{ num_workers }}"
        count_tag:
          Role: "worker"
        wait: yes
      register: wrk

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: workers
      with_items: "{{ wrk.instances }}"

    - name: Wait for workers' SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 900
        state: started
      with_items: "{{ wrk.instances }}"

- name: Provision master
  hosts: tag_Role_master
  remote_user: ubuntu
  become: true
  gather_facts: true
  # Keep this ahead of vars_files
  vars:
    update_apt_cache: true
    broker_ip: "{{ hostvars[groups['tag_Role_master'][0]].ansible_default_ipv4.address }}"
  vars_files:
    - env_vars/base.yml
    - env_vars/aws.yml
    - env_vars/domains.yml
    - roles/base/defaults/main.yml
  pre_tasks:
    - debug: var=broker_ip
    - name: Set authorized key for Ilya
      authorized_key:
        user: ubuntu
        state: present
        key: https://github.com/ilyasergey.keys
    - name: Set authorized key for backup server
      authorized_key:
        user: ubuntu
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDlCwqe1p+F3BLbupieSaAmjF/suCg+fRH8DX63sMq15tJy4kQHosUVhExfh4xOD8Q0tkRjh8SilCbL9v1gLHrOlcBNj8lXR/d3WfTzii8t4WpjxKasa/l8OtoXKwUkSZMKcWy6cX3T0pu48WVNiVQpE2PwyOe8vEn5pDFzTVxn4WbLeSFrQOOx5FY0uBTXx2pdVubhaWZQ/+GSF9vbyR5Mb0R5w6UZOJk5oymZrjQg+lHBGXB/t2FWUtf75ppXtQ+4loHvBXHzx+SU0bAHQhJTqmMhtdWtkPMp6rGe7sgDW6a3bZldX86ELDD7fbBTfTj1q6mk9lwoa2jiB0Qs2n8SddS/BhmnRBxl03QTFaPZdj2kOhboCubNXL9mU+ScCKTBiB8hxB7u8dJ2MT2qQ0aLx3WpOeEg7135zg9YFXTUdsjpYk+TklQyFZL8oF32qGFtCdEZAXDmmL7DVWn5OUFXyfyWa78AfIBdWWDDJtpVNHuOR8LiOHEGaWjxo06r6uZzTVOeNOql1IoPuja5t1EkJ1AAkSY+/bbvsSIySlG+2l34EauwKOB/MU0x0OHbEGqP1HTUPuKVBobaPbuhHsvrq9lGjmZOjoZUP0HAefEVOySFLULQYPqauzIZm+rH+j7kBDq80rUj8Nmon7qfd+PPV5Gv/4BqeLp+OnjJxtYnHw== sergey@sergey-icfp"
  roles:
    - efs
    - base
    - app-base
    - problems
    - cron
    - rabbitmq
    - flower
    - notifytimer
    - nginx
    - certbot
    - web

- name: Provision {{ num_workers }} workers
  hosts: tag_Role_worker
  remote_user: ubuntu
  become: true
  gather_facts: true
  # Keep this ahead of vars_files
  vars:
    update_apt_cache: true
    broker_ip: "{{ hostvars[groups['tag_Role_master'][0]].ansible_default_ipv4.address }}"
  vars_files:
    - env_vars/base.yml
    - env_vars/aws.yml
    - roles/base/defaults/main.yml
  pre_tasks:
    - debug: var=broker_ip
    - name: Set authorized key for Ilya
      authorized_key:
        user: ubuntu
        state: present
        key: https://github.com/ilyasergey.keys
  roles:
    - efs
    - base
    - app-base
    - celery
