---
- hosts: all
  become: true
  vars:
    update_apt_cache: true
    broker_ip: 192.168.33.10

  vars_files:
    - env_vars/base.yml
    - env_vars/domains.yml
    - roles/base/defaults/main.yml
    
  roles:
    - base
    - app-base
    - problems
    - cron
    - rabbitmq
    - flower
    - nginx
    - web
    - web-static
 