---

- include: setup_gunicorn.yml
  tags: gunicorn

- include: setup_flask_app.yml
  tags: deploy

- include: setup_supervisor.yml
  tags: supervisor

- name: Restart Gunicorn
  command: echo "Restart Gunicorn"
  notify: restart {{ application_name }}