---

server_root_dir: /webapps

virtualenv_path: "/webapps/{{ project_name }}"
project_path: "{{ virtualenv_path }}/{{ application_name }}"

celery_user: "{{ application_name }}"
celery_group: webapps

celery_num_workers: "{{ ansible_processor_vcpus }}"

celery_application_name: celery
celery_scripts_dir: "{{ virtualenv_path }}/scripts/celery"
celery_template_file: "{{ celery_application_name }}_start.j2"

celery_log_dir: "{{ persistent_dir }}/logs"
celery_log_file: "{{ celery_log_dir }}/{{ celery_application_name }}-{{ ansible_hostname }}.log"
