---

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_git_repo.yml
  tags: deploy

- include: install_reqs.yml
  tags: deploy

- include: copy_jar.yml
  tags: deploy
